# netlify.toml - VERSÃO CORRIGIDA
[build]
  functions = "netlify/functions"
  publish = "."

# ============================================
# AGENDAMENTO AUTOMÁTICO - HORÁRIO EDITÁVEL
# ============================================
# SEMPRE pega do dia 1 do mês atual até hoje
# Horário atual: 15:30 Brasília = 18:30 UTC

[[plugins]]
  package = "netlify-plugin-cron"
  
  [plugins.inputs]
    schedule = "30 18 * * *"  # Todo dia às 15:30 (horário de Brasília)
    url = "/.netlify/functions/cron-scheduler"

# ============================================
# CONFIGURAÇÃO DE HEADERS PARA CORS
# ============================================
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

# ============================================
# REDIRECIONAMENTOS ÚTEIS
# ============================================
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# ============================================
# CONFIGURAÇÕES DE BUILD E DEPLOY
# ============================================
[build.environment]
  NODE_VERSION = "18"

# ============================================
# CONVERSÕES ÚTEIS (Brasília → UTC):
# ============================================
# 14:00 BRT = 17:00 UTC = "0 17 * * *"
# 14:30 BRT = 17:30 UTC = "30 17 * * *"
# 15:00 BRT = 18:00 UTC = "0 18 * * *"
# 15:30 BRT = 18:30 UTC = "30 18 * * *"  ← ATUAL
# 16:00 BRT = 19:00 UTC = "0 19 * * *"
# 16:30 BRT = 19:30 UTC = "30 19 * * *"
# 17:00 BRT = 20:00 UTC = "0 20 * * *"
# 18:00 BRT = 21:00 UTC = "0 21 * * *"