# netlify.toml - VERSÃO CORRIGIDA PARA DEPLOY
[build]
  functions = "netlify/functions"
  publish = "."
  command = "echo 'Build estático concluído'"

# ============================================
# CONFIGURAÇÃO DE HEADERS PARA CORS
# ============================================
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

# ============================================
# REDIRECIONAMENTOS ÚTEIS
# ============================================
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# ============================================
# CONFIGURAÇÕES DE BUILD E DEPLOY
# ============================================
[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"

# ============================================
# CONFIGURAÇÃO DE FUNÇÕES
# ============================================
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# ============================================
# NOTA: Plugin de CRON removido
# Use agendadores externos como GitHub Actions
# ou crie webhooks manuais para automação
# ============================================